// <auto-generated />
namespace ModelsLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _990212 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_990212));
        
        string IMigrationMetadata.Id
        {
            get { return "202005010742405_990212"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
